{
 "title": "Restaurant Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chefs working",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Restaurant_active_chefs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Restaurant_order_queue_size", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Chefs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "Restaurant_active_chefs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order Queue over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "Restaurant_order_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Made per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(Restaurant_pizza_made_total[$__interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas per amount of time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Restaurant_pizza_making_duration_seconds_bucket)by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}